### PR TITLE
Document how to test publishing in development

### PR DESCRIPTION
**Pull request by jennyd**
I've added this at the bottom of the README (rather than with the request
documentation) because most of the file is documentation of the API for HMRC
rather than for GDS developers.

Also change the level of the tagging headings and fix a space character in another heading.

### CODE REVIEW

**Comment by jennyd** [comment]
Please could other people try the curl command out? I used `--data-binary` because I got an encoding error with `--data` but @mikejustdoit gets the error with `--data-binary`...

```
Encoding::UndefinedConversionError in ManualsController#update
"\xE2" from ASCII-8BIT to UTF-8
```

**Comment by mikejustdoit** [comment]
I can reproduce the error using `--data`, but it's raised from a different place.

The `--data` error's trace:
`render json: { status: "error", errors: [message] }, status: 400` (that's line 28 as mentioned below)
```
app/controllers/application_controller.rb:28:in `rescue in parse_request_body'
app/controllers/application_controller.rb:25:in `parse_request_body'
```

**Comment by mikejustdoit** [comment]
And the `--data-binary` error's trace:
`publishing_api_response = HMRCManualsAPI.publishing_api.put_content_item(base_path, to_h)` (<-- this is line 64 as mentioned below)
```
app/models/publishing_api_manual.rb:64:in `save!'
app/controllers/manuals_controller.rb:7:in `update'
```

**Comment by alext** [comment]
It's probably erroring because `public/json_examples/requests/employment-income-manual.json` isn't a valid JSON file (it has comments in it).

**Comment by dsingleton** [comment]
Using `--data-binary` this works for me, but `--data` fails.

Removing the comments from the `json_example` makes `--data` work too. 

@mikejustdoit is going to see if that fixes it for him too. If so we can move the sentiment of the comments somewhere else (`README`, or description in `manual-schema.json`).

**Comment by mikejustdoit** [comment]
Updated and re-provisioned my VM and I started getting 200s back, with and without comments in the JSON :+1:

**Comment by dsingleton** [comment]
:tada:

**Pull request merged**
