### PR TITLE
Run tests on CI.

### PR DESCRIPTION
**Pull request by sengi**
This app uses rspec and not minitest, but we were only running the minitest action.

### CODE REVIEW

**Comment by sengi** [comment]
Oh, it does need the content schemas from publishing-api after all. My bad.

**Comment by jkempster34** [comment]
Is this bit in GitHub's UI just leftover from the previous version? 
image

**Comment by sengi** [comment]
That's the bit that needed changing — https://github.com/alphagov/govuk-saas-config/pull/176

**Review by jkempster34 — APPROVED** [review]

**Comment by jkempster34** [comment]
> That's the bit that needed changing — [alphagov/govuk-saas-config#176](https://github.com/alphagov/govuk-saas-config/pull/176)

Ah, gotcha. Thank you!

**Pull request merged**
